---

#
# Copyright (c) 2014 Davide Guerri <davide.guerri@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Dump service tenant id
  shell: keystone tenant-get service | awk '/ id / {print $4}'
  register: service_tenant_id
  changed_when: false
  environment: openstack_service_env
  when: not nova_admin_tenant_id

- name: Configure Neutron Database
  ini_file: dest=/etc/neutron/neutron.conf
            section="{{ item.section }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items:
    - section:  database
      option:   connection
      value:    "{{ neutron_database_url }}"
  notify:
    - Restart Neutron server

- name: Configure Neutron
  ini_file: dest=/etc/neutron/neutron.conf
            section="{{ item.section }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items:
    - section:  database
      option:   connection
      value:    "{{ neutron_database_url }}"
    - section:  DEFAULT
      option:   api_paste_config
      value:    "{{ neutron_api_paste }}"
    - section:  DEFAULT
      option:   bind_host
      value:    "{{ neutron_bind_host }}"
    - section:  DEFAULT
      option:   bind_port
      value:    "{{ neutron_port }}"
    - section:  DEFAULT
      option:   auth_strategy
      value:    keystone
    - section:  DEFAULT
      option:   api_paste_config
      value:    "{{ neutron_api_paste }}"
    # RabbitMQ
    - section:  DEFAULT
      option:   rpc_backend
      value:    neutron.openstack.common.rpc.impl_kombu
    - section:  DEFAULT
      option:   rabbit_host
      value:    "{{ neutron_rabbit_hostname }}"
    - section:  DEFAULT
      option:   rabbit_userid
      value:    "{{ neutron_rabbit_userid }}"
    - section:  DEFAULT
      option:   rabbit_password
      value:    "{{ neutron_rabbit_password }}"
    - section:  DEFAULT
      option:   rabbit_virtual_host
      value:    "{{ neutron_rabbit_virtual_host }}"
    - section:  DEFAULT
      option:   rabbit_retry_interval
      value:    "{{ neutron_rabbit_retry_interval }}"
    - section:  DEFAULT
      option:   rabbit_hosts
      value:    "{{ neutron_rabbit_hosts }}"
    - section:  DEFAULT
      option:   rabbit_ha_queues
      value:    "{{ neutron_rabbit_ha_queues }}"
    - section:  DEFAULT
      option:   notify_nova_on_port_status_changes
      value:    True
    - section:  DEFAULT
      option:   notify_nova_on_port_data_changes
      value:    True
    - section:  DEFAULT
      option:   nova_url
      value:    "{{ nova_protocol }}://{{ nova_api_hostname }}:{{ nova_port }}/v2"
    - section:  DEFAULT
      option:   nova_admin_tenant_id
      value:    "{{ service_tenant_id.stdout }}"
    - section:  DEFAULT
      option:   nova_admin_username
      value:    "{{ nova_user }}"
    - section:  DEFAULT
      option:   nova_admin_password
      value:    "{{ nova_pass }}"
    - section:  DEFAULT
      option:   nova_admin_auth_url
      value:    "{{ keystone_protocol }}://{{ keystone_hostname }}:{{ keystone_admin_port }}/v2.0"
    - section:  DEFAULT
      option:   core_plugin
      value:    ml2
    - section:  DEFAULT
      option:   service_plugins
      value:    router
    - section:  DEFAULT
      option:   allow_overlapping_ips
      value:    True
    - section:  DEFAULT
      option:   log_dir
      value:    "{{ neutron_log_dir }}"
    - section:  DEFAULT
      option:   log_debug
      value:    "{{ neutron_log_debug }}"
    - section:  DEFAULT
      option:   log_verbose
      value:    "{{ neutron_log_verbose }}"
    - section:  keystone_authtoken
      option:   auth_uri
      value:    "{{ keystone_protocol }}://{{ keystone_hostname }}:{{ keystone_port }}"
    - section:  keystone_authtoken
      option:   auth_host
      value:    "{{ keystone_hostname }}"
    - section:  keystone_authtoken
      option:   auth_port
      value:    "{{ keystone_admin_port }}"
    - section:  keystone_authtoken
      option:   auth_protocol
      value:    "{{ keystone_protocol }}"
    - section:  keystone_authtoken
      option:   admin_tenant_name
      value:    service
    - section:  keystone_authtoken
      option:   admin_user
      value:    "{{ neutron_user }}"
    - section:  keystone_authtoken
      option:   admin_password
      value:    "{{ neutron_pass }}"
  notify:
    - Restart Neutron server
